[theme]
backgroundColor = "#F5F7FA"  # Light Gray for a professional background
secondaryBackgroundColor = "#E5E7EB"  # Light Gray for sidebar
primaryColor = "#3B82F6"  # Bright Blue for buttons and highlights
textColor = "#1F2937"  # Dark Gray for readability
font = "sans serif"